<div id="inicio">
<p>Seja bem vindo ao DataSIG.</p>
<p>Você pode acessar seus projetos ao lado...</p>
<p>...ou buscar um projeto existente para ingressar na barra acima</p>
<p>Também é possível criar um projeto do zero e aguardar colaboradores. <br /> Que tal começar agora?</p>
<a href="<?=$this->url(array('controller'=>'projeto','action'=>'criar'),null,true)?>" class="link_inicio"> Criar Projeto </a>  
</div>