    <!DOCTYPE HTML>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="/datasig/public/css/estilo_2.css">
    <link rel="stylesheet" type="text/css" href="/datasig/public/css/estilo_body.css">
    <title>DataSIG</title>
  </head>
    <body>
      <div id="limite">
      <div id="red_bar">
                <nav id="nav_principal">
                    <div id="nav_p_logo">
                        <a class="no_style" href="<?=$this->url(array('controller'=>'index','action'=>'index'),null,true)?>">Data<span class="logo_y">SIG</span></a>
                    </div>
                    <div id="nav_p_itens">
                        <a><?=$this->login?> |</a>
                        <a href="<?=$this->url(array('controller'=>'autenticacao','action'=>'logout'),null,true)?>">SAIR</a>
                         <form action="<?=$this->url(array('controller'=>'projeto','action'=>'buscas'),null,true)?>">
                             <input placeholder="buscar" name="busca"/>
                             <input type="submit" class="buscas" value="Ir">
                         </form>
                       <!-- <ul>
                            <li><a href="#">O</a></li>
                            <li><a>X</a></li>
                            <li><a>@</a></li>
                        </ul>-->
                    </div>
                </nav>
      </div>    
      </div>
         <div id="geral">
            <nav id="sidebar">
                <ul>
                    <div id="sidebar_block">
                       <li><a href="#">Olá, <?=$this->login?> <?=$this->sobre?></a></li>
                    </div>
                    <div id="sidebar_block">
                      <li><a href="#">Projetos</a></li>
                        <ul class="inside">
                        <?php foreach($this->projetos as $projeto): ?>
                            <li><a href="<?=$this->url(array('controller'=>'projeto','action'=>'visualizar', 'id' => $projeto['id_projeto']),null,true)?>"><?= $projeto['nome_projeto']?> </a></li>
                         <?php endforeach;?>
                        </ul>
                    </div>
                </ul>
            </nav>
             <div id="bloco_total">
                <?php echo $this->layout()->content; ?>
             </div>
        </div>
    </body>
    </html>