           <div id="bloco_1">
              <div id="b1_coluna_1">
                <h1>Formulário</h1>
                <ul class="lista_tarefas_corpo">
                  <li>Região</li>
                  <li>NH4</li>
                  <li>SO3</li>
                  <li>NO4</li>
                  <li>PH</li>
                  <li>Coliformes</li>
                  <li>O2</li>
                </ul>
              </div>
              <div id="b1_coluna_2">
                  <h1>Colaboradores</h1>
                <ul class="lista_tarefas_corpo">
                  <li>Gabriel Ganem</li>
                  <li>Martha Magda</li>
                  <li>Francisco Bruno</li>
                  <li>Batman</li>
                  <li>Jorge Amado</li>
                  <li>Tio Patinhas</li>
                  <li>Palmito</li>
                  <li>Lambreta</li>
                  <li>Bill Gates</li>
                  <li>Ghandi</li>
                  <li>Zé Dirceu</li>
                </ul>
              </div>
            </div>
           <div id="bloco_2">
             <h1>Últimas Coletas</h2>
             <ul class="feed">
                <li>
                  <div id="div_feed">
                    <div id="div_feed_img"></div>
                    <div id="div_feed_assunto">
                        <h1>Gabriel Ganem</h1>
                        <h2>16:30 </h2>
                    </div>
                   
                  </div>
                </li>
               <li>
                  <div id="div_feed">
                    <div id="div_feed_img"></div>
                    <div id="div_feed_assunto">
                        <h1>Martha Magda</h1>
                        <h2>16:30 - Documentos</h2>
                    </div>

                  </div>
                </li>
               <li>
                  <div id="div_feed">
                    <div id="div_feed_img"></div>
                    <div id="div_feed_assunto">
                        <h1>Gabriel Ganem</h1>
                        <h2>16:30 - Software</h2>
                    </div>
                  </div>
                </li>
                                 <li>
                  <div id="div_feed">
                    <div id="div_feed_img"></div>
                    <div id="div_feed_assunto">
                        <h1>Gabriel Ganem</h1>
                        <h2>16:30 </h2>
                    </div>
                   
                  </div>
                </li>
               <li>
                  <div id="div_feed">
                    <div id="div_feed_img"></div>
                    <div id="div_feed_assunto">
                        <h1>Martha Magda</h1>
                        <h2>16:30 - Documentos</h2>
                    </div>

                  </div>
                </li>
               <li>
                  <div id="div_feed">
                    <div id="div_feed_img"></div>
                    <div id="div_feed_assunto">
                        <h1>Gabriel Ganem</h1>
                        <h2>16:30 - Software</h2>
                    </div>
                  </div>
                </li>
                                 <li>
                  <div id="div_feed">
                    <div id="div_feed_img"></div>
                    <div id="div_feed_assunto">
                        <h1>Gabriel Ganem</h1>
                        <h2>16:30 </h2>
                    </div>
                   
                  </div>
                </li>
               <li>
                  <div id="div_feed">
                    <div id="div_feed_img"></div>
                    <div id="div_feed_assunto">
                        <h1>Martha Magda</h1>
                        <h2>16:30 - Documentos</h2>
                    </div>

                  </div>
                </li>
               <li>
                  <div id="div_feed">
                    <div id="div_feed_img"></div>
                    <div id="div_feed_assunto">
                        <h1>Gabriel Ganem</h1>
                        <h2>16:30 - Software</h2>
                    </div>
                  </div>
                </li>
             </ul>
           </div>